version: '3'
services:
  app:
    image: node:lts
    container_name: node_app
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["node", "/app/src/index.js"]
    mem_limit: "512m"  # Limita la memoria a 512MB
